import 'package:dio/dio.dart';

class MusicSurveyService {
  final Dio _dio = Dio();
  Future<void> postMusicData(
      {required int age,
      required String primaryStreamingService,
      required double hoursPerDay,
      required String whileWorking,
      required String instrumentalist,
      required String composer,
      required String favGenre,
      required String exploratory,
      required String foreignLanugage,
      required int bpm,
      required String frequencyClassical,
      required String frequencyCountry,
      required String frequencyEDM,
      required String frequencyFolk,
      required String frequencyGospel,
      required String frequencyHipHop,
      required String frequencyJazz,
      required String frequencyKPop,
      required String frequencyLatin,
      required String frequencyLofi,
      required String frequencyMetal,
      required String frequencyPop,
      required String frequencyRB,
      required String frequencyRap,
      required String frequencyRock,
      required String frequencyVideoGameMusic,
      required int anxiety,
      required int depression,
      required int insomnia,
      required int ocd,
      required String musicEffects,
      required String permissions}) async {
    const String url = 'http://localhost:5000/submit_music';
    final Map data = {
      'timestamp': DateTime.timestamp(),
      'age': age,
      'primary_streaming_service': primaryStreamingService,
      'hours_per_day': hoursPerDay,
      'while_working': whileWorking,
      'instrumentalist': instrumentalist,
      'composer': composer,
      'fav_genre': favGenre,
      'exploratory': exploratory,
      'bpm': bpm,
      'frequency_classical': frequencyClassical,
      'frequency_country': frequencyCountry,
      'frequency_edm': frequencyEDM,
      'frequency_folk': frequencyFolk,
      'frequency_gospel': frequencyGospel,
      'frequency_hip_hop': frequencyHipHop,
      'frequency_jazz': frequencyJazz,
      'frequency_k_pop': frequencyKPop,
      'frequency_latin': frequencyLatin,
      'frequency_lofi': frequencyLofi,
      'frequency_metal': frequencyMetal,
      'frequency_pop': frequencyPop,
      'frequency_r&b': frequencyRB,
      'frequency_rap': frequencyRap,
      'frequency_rock': frequencyRock,
      'frequency_video_game_music': frequencyVideoGameMusic,
      'anxiety': anxiety,
      'depression': depression,
      'insomnia': insomnia,
      'ocd': ocd,
      'music_effects': musicEffects,
      'permissions': permissions
    };
    await _dio.post(url, data: data);
  }
}
